tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mas-cli/tap"
brew "arp-scan"
brew "bash"
brew "bash-completion@2"
brew "brew-cask-completion"
brew "clang-format"
brew "coreutils"
brew "findutils"
brew "get-flash-videos"
brew "git"
brew "gnu-sed"
brew "jq"
brew "mas"
brew "moreutils"
brew "pcre"
brew "tree"
brew "wget"
cask "1password"
cask "alfred"
cask "amadine"
cask "appcleaner"
cask "arduino"
cask "backblaze"
cask "balenaetcher"
cask "calibre"
cask "coolterm"
cask "dash"
cask "dropbox"
cask "fantastical"
cask "firefox"
cask "flux"
cask "istat-menus"
cask "iterm2"
cask "karabiner-elements"
cask "logitech-options"
cask "omnidisksweeper"
cask "omnifocus"
cask "pdf-expert"
cask "racket"
cask "rocket"
cask "saleae-logic"
cask "simple-comic"
cask "slack"
cask "sublime-merge"
cask "sublime-text"
cask "tg-pro"
cask "the-unarchiver"
cask "vanilla"
cask "vlc"
cask "wireshark"
cask "zoom"
mas "Bear", id: 1091189122
mas "Brother P-touch Editor", id: 1453365242
mas "Day One", id: 1055511498
mas "Deliveries", id: 290986013
mas "Fantastical", id: 975937182
mas "Magnet", id: 441258766
mas "ReadKit", id: 588726889
mas "Spark", id: 1176895641
mas "Tailscale", id: 1475387142
mas "Tweetbot", id: 1384080005
mas "Xcode", id: 497799835
mas "Yoink", id: 457622435